### ISSUE TITLE
Frideos library example app

### ISSUE THREAD

**Issue by frideosapps** [brianegan/flutter_architecture_samples#116]
Hello, I've made an example with [my package](https://github.com/frideosapps/frideos_flutter), it is just a library to make a little bit easier using streams. I'd really like to contribute with a PR.

**Comment by brianegan** [comment]
Hey there :) That'd be great!

Please review the App Specifications and implement as much of it as possible! https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md

If you run into trouble implementing something, feel free to open a PR and we can work through it!

**Comment by frideosapps** [comment]
Thanks! I'll do my best to adapt it to follow the correct implementation.

**Comment by frideosapps** [comment]
Hello Brian! I updated the sample to follow the guidelines, I hope it is correct. By the way, running the integration test I am facing this error: "/integration_tests.dart:18:44: Error: No named parameter with the name 'timeoutMultiplier'.  driver = await FlutterDriver.connect(timeoutMultiplier: 4);". If I remove the timeoutMultiplier parameter the test runs find and the app passes all tests.

This is the branch of my fork with the sample:
https://github.com/frideosapps/flutter_architecture_samples/tree/frideos_library/frideos_library

**Comment by mmcc007** [comment]
The timeout multiplier is a feature the Flutter Team added a few months ago:
https://github.com/flutter/flutter/issues/23857

But in the most recent release(s), for some reason it is missing. Not clear why.

Because the android emulator runs like molasses (slow) in the cloud this means the project can't easily upgrade to most recent version of Flutter without the android integration tests timing out. (though there is a good change it will work, if we but back the per-driver-call-timeouts we had before in the integration tests). 

So for now I would say feel free to add the per-driver-call-timeouts back into integration tests in your related upcoming PR. There is a good chance they will work. This is the PR where I removed them:
https://github.com/brianegan/flutter_architecture_samples/pull/91/files

Otherwise, I would say, leave the timeoutMultiplier intact. This would require downgrading to an earlier version of Flutter that still has the timeoutMultiplier using something like:
```
flutter version --force v1.0.0
```

(When the missing timeoutMultiplier issue is resolved, we can then decide on how to move forward.)

**Comment by mmcc007** [comment]
I created an issue  regarding the missing timeoutMultiplier feature at https://github.com/flutter/flutter/issues/28811

**Comment by frideosapps** [comment]
Thanks for the explanation! Downgrading to flutter to v1.0.0 the integration tests run fine as expected. I'm going to send the PR with no modification of the timeoutMultiplier.
