### ISSUE TITLE
Brian's Architectural Paragon

### ISSUE THREAD

**Issue by exo-pla-net** [brianegan/flutter_architecture_samples#127]
It seems that I and many others are looking to you for best practices in making a Flutter app.

There's something to be said about being agnostic about different approaches in order to cater to different backgrounds/needs. But for many developers, we're learning Flutter with zero baggage and only simple needs for our apps, and we only care about best practices, so we don't hit unexpected walls and have to redo/unlearn things later. You, having experienced the ins and outs of so many different approaches, seem uniquely positioned to tell us what the best approach for most people in most situations probably is.

I've gleaned for instance that BLoC is a great idea, but the edges of actually implementing it in a Flutter app haven't yet been smoothed out. Scoped_model is fully-fledged and gets the job of managing app state done, at the slight expense of being unable to recycle as much of your code for a web implementation compared to a pure BLoC approach.

Accordingly, what I would love to see is your ToDo sample independently bundled from top to bottom using Scoped Model. It could then serve as an architectural paragon for us, so we can follow your lead and defer to your better judgment. I'm currently trying to piece together your hard earned wisdom from your _todos_core_ imports to determine how a full app would look, and it remains unclear. There's a lot of code that's dedicated to juggling the various app state management samples.

What I'd specifically like to see is how you think we ought to organize our app in terms of directories, and how routing would look. I know that dropping single files into their own directory is frowned upon, but most of our apps will be larger than your ToDo app, and we'd like to know how to keep things sanely organized without it collapsing into chaos as the app gets larger. I intuit that Brian's Paragonic Architecture Example, with a directory structure that provides room to grow, would look something like:

- /lib/
- - /src/
- - - /screens/ -- screens and any tiny widgets on them
- - - /widgets/ -- shared widgets and big widgets
- - - /localization/
- - - /repository/ -- CRUD implementation
- - - /models/ -- scope-able models
- - - - /src/ -- entities that live in the scoped models
- - - routes.dart
- - - theme.dart
- - main.dart 

I'm sure that something is wrong here, but this perhaps illustrates what I mean. Directory structure is important not just for organization but also in terms of how you _think_ about an app, and currently no good Flutter paragon seems to exist out there. It's all bits and pieces. Having a paragon to look to and learn from would be tremendously helpful for me, at least, and I highly suspect I'm not alone.

**Comment by brianegan** [comment]
> There's something to be said about being agnostic about different approaches in order to cater to different backgrounds/needs. But for many developers, we're learning Flutter with zero baggage and only simple needs for our apps, and we only care about best practices, so we don't hit unexpected walls and have to redo/unlearn things later.

Hey, I totally feel ya on this one! I think it'd be great for more examples like that to exist -- there are only a couple out there right now that I can think of: inKino and invoice ninja. Both of those use Redux as their architecture instead of scoped model, however. 

Overall, the goal of this project is to provide an "Apples to Apples" comparison between different architectural choices. Therefore, I don't quite think this is the right repository for such a complete example -- as you said, I think the app would have to be more complex than a todo app to really highlight different techniques from directory structure and beyond.

However, I've been slowly working on another project to fill the gap you've described. It's not anywhere near completion since it's a large undertaking, but hopefully it will help out!

Since I don't quite think this repo is the right place for a larger architectural sample using a single architecture, I'm gonna go ahead and close this out for now, but want ya to know I hear ya and will hopefully publish something in the next couple of months!
