### ISSUE TITLE
[Question] Setting Keys

### ISSUE THREAD

**Issue by hffmnn** [brianegan/flutter_architecture_samples#147]
Hi there,

I am new to flutter so maybe this question has an obvious answer, but looking at other flutter example code, more ore less no one is using `Key`s on widgets as extensively as it is done in this repository (if at all). There is even an explicit file for it: https://github.com/brianegan/flutter_architecture_samples/blob/master/todos_app_core/lib/src/keys.dart

Can someone elaborate about:

* policies when a `Key` should be used
* if there are any benefits using (some of) this keys (I removed some of the keys and could not see any visual difference)

Thanks in advance

**Comment by brianegan** [comment]
Hi @hffmnn -- Thanks for writing in! The best advice for when to use keys comes from the Flutter team: https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d

So why does this Repo make such use of Keys and have a separate file, while many others don't? For integration testing! All apps submitted to this repo must pass the [integration test suite](https://github.com/brianegan/flutter_architecture_samples/tree/master/integration_tests) so we can verify the app works according to the spec without having to manually check every last detail on every change.

In general, integration tests need some way to look for specific Widgets so they can Tap, Drag, or otherwise interact with the Widget. The best way I've found to target specific Widgets is by using `ValueKey`s to identify specific Widgets: https://flutter.dev/docs/cookbook/testing/integration/introduction

You'll see no change as a user if you remove the keys, but you will see a bunch of integration tests fail if you remove them and try to run the test suite.

Hope that helps!

**Comment by hffmnn** [comment]
Hi @brianegan -- Thanks a lot for your response and yes, that helped a lot. It makes perfect sense to me now and I learned a lot by looking through the links you provided.

Thanks again for this great repository and all of the other Open Source code you provided!
