### ISSUE TITLE
Application state is set outside of the Redux Store, specifically navigation route

### ISSUE THREAD

**Issue by kinggolf** [brianegan/flutter_architecture_samples#15]
Is there a practical method to add route/navigation to the Redux AppState? In the redux example of this repo, DetailsScreen in detail_screen.dart and HomeScreen in home_screen.dart, both presentations components, are setting the state of the app via the Navigator. I am trying to figure out a way to include the route in the AppState and then implement subsequent routes outside presentation components, possibly through Middleware. I have failed thus far. :(

Much like the app presents the active tab via the store, I think the app should present the route via the store. Is this reasonable?

BTW - thanks so very much for this repo, it has been a great help to me getting off the ground with Flutter, Redux, and Dart.

**Comment by brianegan** [comment]
This is a good question, and something I've thought a bit about as well. These are only my ideas, so would be happy to hear yours in response!

First of all, I wouldn't worry about putting absolutely everything into your Redux store, and I believe the Navigator is one of those cases. Why? Because the Navigator handles a lot of things: back button support, animations between screens, showing back arrows in the App Bar, deep linking, etc, and I generally don't think these things should be the responsibility of the Redux Store.

See also this series of tweets from the original Redux author: https://twitter.com/dan_abramov/status/727278247264833536?lang=en

Therefore, I think the best way to pass data between routes is actually through named routes with query parameters. My main reason: To handle all Routes in the same way, especially deep links, which are really important to handle gracefully. 

The only problem I have with using named routes at this time: handling query params in routes with Flutter is a bit clunky at the moment. You need to write your own [`onGenerateRoute`](https://docs.flutter.io/flutter/material/MaterialApp/onGenerateRoute.html) method to parse the query params yourself. However, I think doing that is still the best way to go. 

For example, in the Redux example, I think I should refactor this line: https://github.com/brianegan/flutter_architecture_samples/blob/3b4e271270654a444375f1539b4300f4414cebe6/example/redux/lib/presentation/todo_list.dart#L75

To be `Navigator.of(context).pushNamed('/todos/${todo.id});`, and then write an `onGenerateRoute` implementation that finds extracts `id` of the `Todo` from the named route and then creates a new `EditScreen` or `DetailsScreen` using that parsed Id.

That way, even if someone links to your app from another app, they could link to `/todos/1` and your app would handle it just fine!

--------------------

If you still want to sync the Router with the Store, I think you could totally do it! 

For example:

  1. Create a `RouteObserver` that takes in a `Store`
  2. Create your Store and give it to the `RouteObserver`
  3. Pass the `RouteObserver` your `MaterialApp`.
  4. When the `didPush` or `didPop` methods are called, dispatch an action `DidPopAction` or `DidPushAction` with the `route`.
  5. Create a `route` field in your `AppState`
  6. When the `DidPushAction` or `DidPopAction` reaches your reducer, set the current `route` in your `AppState` to that payload!

So, that's a lot of writing haha, whatcha think overall?

**Comment by kinggolf** [comment]
Thank you @brianegan for your words and your time. I was concerned about including the routes in the store, as I was not sure if the navigation would work as well, but I also am interested in giving it a try, which is why I asked my question.

My background is Javascript, in particular Angular, and I have used ngrx (Angular version of Redux) in several apps. The app that I am currently working on in Flutter certainly does not require Redux, it is fairly simple, but it could grow in complexity and I want to learn how to use Redux in Flutter for possible use in other apps.

Thanks again and I will keep you updated on what I learn. Cheers!

**Comment by brianegan** [comment]
@kinggolf Sure thing! Would love to hear what ya learn. Ya, definitely only bring in Redux patterns when you feel they're necessary.

To make Redux work a bit more like ngrx with "effects," you can check out the `redux_epics` package: https://pub.dartlang.org/packages/redux_epics

Also, I haven't written much about it or put as much time into documentation / flutter integrations, but if you like the full `ngrx` approach, I ported something similar here to see how it worked out: https://pub.dartlang.org/packages/stream_store
