### ISSUE TITLE
Can't run any sample

### ISSUE THREAD

**Issue by esperaking81** [brianegan/flutter_architecture_samples#173]
I am unable to run any of this samples.
I get this error on flutter packages get 
`Because test >=1.6.2 <1.6.4 depends on test_api 0.2.5 and every version of flutter_driver from sdk depends on test_api 0.2.11, test >=1.6.2 <1.6.4 is incompatible with flutter_driver from sdk.
So, because vanilla depends on both flutter_driver any from sdk and test 1.6.2, version solving failed.`
Please let me know if you know how to solve this.
Thanks.

**Comment by brianegan** [comment]
Hrm, that's a bit odd! 

Could you please let me know which version of Flutter you're on? I just tried stable, beta, and master and all seemed to "work on my machine."

Second, is that the entire error message? If not, could you please paste the entire error message? Usually if there's a version conflict, you'll get a summary like "Because X depends on Y, and because Y depends on test 1.6.4, version solving failed." That would help me narrow down the issue as well!

Thanks :)

**Comment by esperaking81** [comment]
Hello !
Thanks for taking your time to look on my issue.

Flutter version: Channel stable, v1.12.13+hotfix.7

Here is the complete output of the error:

`[firestore_redux] flutter packages get
Running "flutter pub get" in firestore_redux...                 
Because test >=1.6.2 <1.6.4 depends on test_api 0.2.5 and every version of flutter_driver from sdk depends on test_api 0.2.11, test >=1.6.2 <1.6.4 is incompatible with flutter_driver from sdk.
So, because fire_redux_sample depends on both flutter_driver any from sdk and test 1.6.2, version solving failed.

pub get failed (1; So, because fire_redux_sample depends on both flutter_driver any from sdk and test 1.6.2, version solving failed.)
exit code 1`

Sorry to bother you :)

**Comment by brianegan** [comment]
Hey -- thanks for that -- no bother at all! 

What's odd is that we don't specifically depend on test 1.6.2 in any pubspec files at this point because we want pub to find the compatible version, but we did specify versions in the past.

Is there any chance you have an old commit of this code, or is this a fresh github clone on the latest version of the master branch?

**Comment by esperaking81** [comment]
I've cloned it in late December 2019.
I'll delete my local repo and clone master again.

**Comment by brianegan** [comment]
Ah, yes -- I've made a bunch of changes since then to fix up this issue and a few others to support the latest stable version. I bet that's it!

**Comment by esperaking81** [comment]
I should've done that before coming here and waste your precious time.
Issue solved !
Thanks you for all the work you doing.
And also thanks for your kind support.

**Comment by brianegan** [comment]
Of course, happy to help! Hope they're useful :)

**Comment by esperaking81** [comment]
> Of course, happy to help! Hope they're useful :)

Very very very very helpful. Am actually working with redux so I wanted to make sure I was following the rules and correct guidelines. I will try the other patterns also.
This repository is a gold mine.
