### ISSUE TITLE
MVI example

### ISSUE THREAD

**Issue by brianegan** [brianegan/flutter_architecture_samples#3]

**Comment by gedw99** [comment]
What's MVI.
Model View I????

**Comment by passsy** [comment]
[Model View Intent](http://hannesdorfmann.com/android/model-view-intent)

**Comment by brianegan** [comment]
JS example here: https://cycle.js.org/model-view-intent.html

Small Flutter example here: https://gitlab.com/brianegan/flutter_mvi_counter

**Comment by gedw99** [comment]
thanks all for the links. read them.
I actually prefer this to Redux..  Here why :
It reminds me of when i used to build CMS systems and you use "Intents" to also navigate across between modules passing "action data with it". These Intents being loosely coupled was very important, because Modules dont known about each other.
Also it allows you to set a "Intent Contex" also which is basically a global context like perhaps a set of name / value pairs, and then each module just does its thing based on that context, leading to a view that can be made up of a ton of different Modules.

**Comment by gedw99** [comment]
This is the same thing you do with GraphQL gateways on the server.
Behind each GraphQL resolver is "modules" which are often GRPC based MicroService's that return the data. When all the data comes back to the GraphQL layerfrom each microservice it goes back up the pipe to the client as a GraphQL response.
