### ISSUE TITLE
PageView built_redux

### ISSUE THREAD

**Issue by palaima** [brianegan/flutter_architecture_samples#31]
Hey 
I would be interested in options integrating PageView Widget for swiping tabs and basically I'm not sure where should PageController go and how it should listen for changes. Any ideas?

**Comment by brianegan** [comment]
Hey, unfortunately I haven't tackled this particular problem with built_redux. @davidmarne do you have any experience with this issue?

**Comment by kinggolf** [comment]
@palaima Do you require PageView only or would Tabs & Scrolling work? Two thoughts on this: 1) Tabs options may be more natural for this repo since @brianegan already has it based on tabs and 2) since individual Todos are already swipe-able for dismissing, then swiping the page or tab could be problematic.

**Comment by palaima** [comment]
I'm thinking of bottom nav bar + scrolling (pages), it's not required to be `PageView` particular

**Comment by kinggolf** [comment]
@brianegan Seems like this can be closed. Over one month since I posted previous comment.

**Comment by brianegan** [comment]
Thanks @kinggolf. I'll go ahead and close it down :) @palaima please feel free to write in again if ya need more help.
