### ISSUE TITLE
error with redux-firestore example on latest flutter beta 

### ISSUE THREAD

**Issue by vbandrade** [brianegan/flutter_architecture_samples#43]
hey everyone,

im trying to run the redux-firestore example on latest flutter beta and I get this error:

```
>gradlew assembleDebug --info > debug.txt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

```

**Comment by brianegan** [comment]
Oh dang, thanks for the heads up. I'll take a look and see what I can do :)

**Comment by kinggolf** [comment]
@vbandrade @brianegan I moved to Flutter beta 3.1 and latest firebase/firestore packages in a separate project, so I applied same learning to firestore_redux within this repo. Here are my steps:
1) edited firebase_flutter_repo/pubspec.yaml, previous version 0.5.3 & 0.5.1 respectively:
```
  firebase_auth: 0.5.5
  cloud_firestore: 0.6.3
```
2) edited firestore_redux/android/build.gradle, google-services from 3.1.0 to 3.2.1 and added maven:
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```
google-services upgraded due to firebase packages now supporting -
`Updated Google Play Services dependencies to version 15.0.0.`
Refer to package change logs.
3) Downloaded google-services.json file to firestore_redux/android/app.
4) Hooked up flutter to repo and ran `flutter packages get`.
The app works fine!

On a side note, I had to update to latest Google Play Services in Android emulator. I found this to be quite a pain & wished I knew a better way to accomplish this.

**Comment by brianegan** [comment]
@kinggolf Thanks so much for taking a look at that! I'll try to apply those changes to the codebase this evening :)

**Comment by brianegan** [comment]
@kinggolf Sorry for the slow response -- traveling a bit. That would be amazing if you have time and if those changes are compatible with the beta branch

**Comment by kinggolf** [comment]
@brianegan NP. I will make the updates and submit a PR. I verified it worked with Beta 0.3.1 previously, so will confirm with latest, Beta 0.3.2. Hope you are enjoying I/O. Cheers!

**Comment by brianegan** [comment]
Amazing. Thanks so much for helping out with this project!

**Comment by brianegan** [comment]
Thanks to @kinggolf, this should be fixed! Please let us know if you run into more trouble :)
