### ISSUE TITLE
Which is more performant ? Built_Redux or flutter_redux ?

### ISSUE THREAD

**Issue by ejabu** [brianegan/flutter_architecture_samples#62]
As you said in [Reddit](https://www.reddit.com/r/FlutterDev/comments/7638tr/flutter_built_redux_flutter_plugin_by_david_marne/)
> Update to my own post -- I've built a more complex example using both Redux and built_redux, and I have to say they're almost identical, especially if you were to use built_value for your State and Action classes.
> A more detailed comparison can be found [here:](https://github.com/brianegan/flutter_architecture_samples/issues/new) 

Which is better in terms of software performance ? with **Built_value** or without **Built_value** ?

**Comment by brianegan** [comment]
built_value might be slightly more performant for two reasons:

  1. It will minimize the number of objects that are created
  2. It will keep a Map of Actions -> Reducers, whereas `flutter_redux` will run each Reducer to see if it needs to handle a specific action. 

However, the cost of running each reducer is very very small, and Dart is particularly well-suited to creating thousands of short-lived objects (it's one reason the Flutter team chose Dart). Therefore, I don't think there's a massive performance difference between the two libraries, and I'd recommend making the choice based on which library you prefer, rather than on the performance of each, unless you're planning on building a massive app with hundreds of thousands of lines of code.

**Comment by ejabu** [comment]
I can't thank you enough ! Thanks

**Comment by brianegan** [comment]
Sure thing!
