### ISSUE TITLE
[Redux] Pop current route after the store has changed ?

### ISSUE THREAD

**Issue by nashfive** [brianegan/flutter_architecture_samples#65]
Hi @brianegan ! First, thanks a lot for all your work on Flutter! That's amazing and very helpful! 

I am currently developing an app in Flutter for a client and I chose the redux way... I currently have a little trouble to manage the navigation. 
Let's say I have a home screen with a Login button. The button simply ask the navigator to push a named route `/login`. The login screen has a form and a `StoreConnector` with a converter that returns a `store.dispatch(LoginAction(formData))`. The `LoginAction` is caught by a specific middleware that will swallow it, do the asynchronous login and finally dispatch a `UserIsLoggedInAction` to the store. 

How can I do this in the login screen itself, since it is something totally asynchronous ? 

What is then the best practice to make the login screen pop?  Should it be triggered by the middleware? If so, it means that I need to inject a `GlobalKey<NavigatorState>` key in all the middlewares that can potentially change the routes? 

It feels a bit fragile to me. I've read on some other threads that we're better off not including the navigation in the app state and let Flutter do its thing with the Navigator, but I am confused on how to synchronize both worlds in terms of navigation, current screen, etc..

Any advice ?

**Comment by nashfive** [comment]
Ok, I took a look at one of your [example about a refresh indicator](https://github.com/brianegan/flutter_redux/blob/refresh-indicator-example/example/lib/main.dart) and I tried to use a `Completable` action. 

In my screen that handles the login form submission, I have this `StoreConnector`:

```dart
StoreConnector<AppState, VoidCallback>(
  converter: (store) => () {
    final completer = Completer()
      ..future
        .then((_) => Navigator.of(context).pop())
        .catchError((e) => print("Error $e"));
      
      store.dispatch(LoginAction(completer: completer));
    },
    builder: (context, callback) {
      return RaisedButton(child: Text("Login"), onPressed: callback);
    }
)
```
So that works, the login screen is correctly popped when the action completes. Do you think it's a valid pattern? I've also come across the `redux_future` package but what I am looking for is more like an action side-effect, that is executed when an action is completed.

**Comment by brianegan** [comment]
Hey @nashfive! Yep, that totally works. In fact, I sometimes think it's a better approach because it keeps all of the "View Logic" contained in the View Layer (e.g. the Widget Layer), and allows the Middleware to be free of any such concerns. They can just concern themselves with doing the work they need to do to talk to the backend / database / whatevs.

Another option could be to create a single `NavigationMiddleware` that handles listens for actions of a certain type and then performs the correct Navigation. That would prevent you from needing to spread the `GlobalKey<NavigatorState>` in different middleware.

Overall, this is one of those areas where Flutter requires a bit more work -- it's reactive in many places, but the Navigator is imperative. You might notice similar tricky spots when you try to use sync other imperative classes, such as `TextEditingController` or `TabController` in combination with Redux (or any stream-based / reactive architecture).

**Comment by nashfive** [comment]
Hi @brianegan and thank you for your answer!
I tried to go the "middleware way", but I wasn't sure how I could fit this in a nice _redux_ way. I would need to manage 4 or 5 actions (2 for push/pop, 3 for login/onSuccess/onFailure) and since my middleware would not update the state, it seems overkill and the Navigator is indeed my middleware ;-) 

In the end, I agree that the Navigator could really use some more work. Until then we have to resort to that kind of tricks... Let's see how it evolves.
