### ISSUE TITLE
All code for examples should be in example dirs

### ISSUE THREAD

**Issue by relativityboy** [brianegan/flutter_architecture_samples#79]
This is clearly and _awesome_ resource for flutter developers.

It's also a *huge* pain in the backside to traverse. Tutorials and examples should be **_fully_** encapsulated.  A dev who wants to traverse a specific example **NOT** thrilled about hoisting themselves right out of the project to understand what the code is doing. It's as nasty as .`window.SomeResourceINeedInVariousPlaces = ...`.

Keep the stuff in `/lib` if you want and then make a script to copy the source to the appropriate example trees. It may seem like a small thing, but those little things are what take products from 
![51ez5ttnxwl](https://user-images.githubusercontent.com/599528/47272255-9fca5880-d548-11e8-9d6d-28374d34171c.jpg)

to

![41uywaprmbl](https://user-images.githubusercontent.com/599528/47272225-3e09ee80-d548-11e8-85b7-8888f6af7e9a.jpg)

**Comment by zerox1212** [comment]
+1, Grabbing the example for firebase immediately has `pubspec` errors for new people like me because parts of the code are in other folders. It's very confusing!

**Comment by mmcc007** [comment]
I started writing a script that builds a new project with the architecture you select.

It builds a new independent project, scans the pubspec.yaml for local dependencies, (also scans the local dependency's pubspec.yaml for more local dependencies), copies all the local dependencies to the new project and fixes the new pubspec.yaml. 

It is working for the vanilla project. The usage looks like:

```
$  dart bin/create_project.dart --help
usage: dart create_project.dart [--help] --arch=<arch name> -name=<project name> --out=<project directory>

    --arch=<vanilla>               Available architectures

          [bloc_flutter]           BloC pattern
          [built_redux]            Redux pattern using generated code
          [firestore_redux]        Redux pattern integrated with a Firestore backend
          [inherited_widget]       Inherited Widget pattern
          [mvi_flutter]            MVI pattern
          [mvu]                    MVU pattern
          [redurx]                 Redurx pattern
          [redux]                  Redux pattern
          [scoped_model]           Scoped Model pattern
          [simple_bloc_flutter]    Simple implementation of BloC pattern
          [vanilla]                Standard Flutter pattern for non-complex apps

    --name=<project name>          Name of project
    --out=<dir>                    Directory location for new project
-h, --help
$
```
Here it is in action:
```
$ dart bin/create_project.dart --arch vanilla --name=vanilla_project --out /tmp
Creating vanilla_project in /tmp. Please wait ...
Creating project vanilla_project...
  vanilla_project/.gitignore (created)
  vanilla_project/.idea/libraries/Dart_SDK.xml (created)
  vanilla_project/.idea/libraries/Flutter_for_Android.xml (created)
  vanilla_project/.idea/modules.xml (created)
  vanilla_project/.idea/runConfigurations/main_dart.xml (created)
  vanilla_project/.idea/workspace.xml (created)
  vanilla_project/.metadata (created)
  vanilla_project/android/app/build.gradle (created)
  vanilla_project/android/app/src/main/java/com/example/vanillaproject/MainActivity.java (created)
  vanilla_project/android/build.gradle (created)
  vanilla_project/android/.gitignore (created)
  vanilla_project/android/app/src/main/AndroidManifest.xml (created)
  vanilla_project/android/app/src/main/res/drawable/launch_background.xml (created)
  vanilla_project/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  vanilla_project/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  vanilla_project/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  vanilla_project/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  vanilla_project/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  vanilla_project/android/app/src/main/res/values/styles.xml (created)
  vanilla_project/android/gradle/wrapper/gradle-wrapper.properties (created)
  vanilla_project/android/gradle.properties (created)
  vanilla_project/android/settings.gradle (created)
  vanilla_project/ios/Runner/AppDelegate.h (created)
  vanilla_project/ios/Runner/AppDelegate.m (created)
  vanilla_project/ios/Runner/main.m (created)
  vanilla_project/ios/Runner.xcodeproj/project.pbxproj (created)
  vanilla_project/ios/.gitignore (created)
  vanilla_project/ios/Flutter/AppFrameworkInfo.plist (created)
  vanilla_project/ios/Flutter/Debug.xcconfig (created)
  vanilla_project/ios/Flutter/Release.xcconfig (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  vanilla_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  vanilla_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  vanilla_project/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  vanilla_project/ios/Runner/Base.lproj/Main.storyboard (created)
  vanilla_project/ios/Runner/Info.plist (created)
  vanilla_project/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  vanilla_project/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  vanilla_project/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  vanilla_project/lib/main.dart (created)
  vanilla_project/vanilla_project.iml (created)
  vanilla_project/vanilla_project_android.iml (created)
  vanilla_project/pubspec.yaml (created)
  vanilla_project/README.md (created)
  vanilla_project/test/widget_test.dart (created)
Running "flutter packages get" in vanilla_project...
Wrote 65 files.

[✓] Flutter is fully installed. (Channel unknown, v0.8.2, on Mac OS X 10.12.6 16G1036, locale en-US)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices is fully installed. (Xcode 9.0.1)
[✓] Android Studio is fully installed. (version 3.2)
[✓] VS Code is fully installed. (version 1.27.2)
[!] Connected devices is partially installed; more components are available.

Run "flutter doctor" for information about installing additional components.

All done! In order to run your application, type:

  $ cd vanilla_project
  $ flutter run

Your main program file is lib/main.dart in the vanilla_project directory.

copying from example/vanilla to /tmp/vanilla_project...
copying from example/vanilla/../../ to /tmp/vanilla_project/flutter_architecture_samples...
copying from example/vanilla/../todos_repository_flutter to /tmp/vanilla_project/todos_repository_flutter...
copying from example/vanilla/../todos_repository to /tmp/vanilla_project/todos_repository...
copying from example/vanilla/../integration_tests to /tmp/vanilla_project/integration_tests...
Your project is ready. Please cd to /tmp/vanilla_project and run "flutter run"
$ cd /tmp/vanilla_project
$ flutter build apk
Running "flutter packages get" in vanilla_project...         0.8s
Initializing gradle...                                       0.7s
Resolving dependencies...                                    0.8s
Running 'gradlew assembleRelease'...                        30.9s
Built build/app/outputs/apk/release/app-release.apk (5.8MB).
$
```

It is working for some other projects too. I'll do a PR when it is working for all projects.

**Comment by mmcc007** [comment]
If this works we could publish it at some point to [pub.dartlang.org/packages](https://pub.dartlang.org/packages/) and activate it using something like
```
$ pub global activate flutter_arch_samples
```
which would download it and add it to the path.

Then you can use it like
```
$ flutter_arch_samples --arch vanilla --out /tmp/vanilla
```

**Comment by brianegan** [comment]
Hey all -- thanks for writing in! Sorry about the delay -- busy travel / work times! 

" It's as nasty as .window.SomeResourceINeedInVariousPlaces = ...." -- I have to say I disagree with this statement. I don't quite see how splitting an app into smaller, reusable libraries is the same as global variables. As apps grow in size, it's quite common to break them down into smaller, independent libraries.

However, I don't want the project to be difficult to look through for new folks, either! Also, I didn't anticipate peeps would copy and paste these projects and use them as a starting point (since you'd have to remove so much code it would become more cumbersome to do that than to start fresh).

Therefore, I like the idea of creating a script or extra package that could generate these folders if that makes the examples easier to read & copy. And for folks who want to read the code to understand how you can break an app down into smaller libs, that would still be available.

**Comment by zerox1212** [comment]
If you know of some better bare-bone starting point projects I would love to know about them. Otherwise this is the only project showing multiple different ways to layout the framework. Most other examples are too simplified (everything in main.dart).

I'm new to flutter. I'm tired of maintaining my app on iOS and Android so I was looking for the fastest way to start a flutter project. Having never used a reactive programming style I found the basic examples confusing and messy (so many nested things and all these calls to `set_state`!).  So I started with this library offers some clarity. Thanks for the effort.

It would be really great if someone could take that script one step further and create a "cookie cutter flutter" repo. https://github.com/audreyr/cookiecutter

**Comment by brianegan** [comment]
Thanks for the additional information, @zerox1212! Glad it's been helpful.

Overall, what you're saying makes a ton of sense. I almost wonder if it might make sense to file a bug on the Flutter repo for that kind of functionality, so you could do something like `flutter create my_awesome_app https://github.com/githubuser/awesome_flutter_template`.

**Comment by relativityboy** [comment]
Appreciate your perspective @brianegan, and your willingness to adapt the repo to community needs. 

@zerox1212 if you file an issue for what he suggested - `flutter create my_awesome_app` I'll second it. Likely they could rip-off some Android Studio code as a starting place.

**Comment by mmcc007** [comment]
Such a `flutter create` option could be useful.

If submitting a feature request, mention that it would be helpful if they could scan the `pubspec.yaml` of the `main()` package to pull in any _actual_ local dependencies (and ignore others).  

In the meantime, it might be useful to have a dedicated command that does this. It seems like a generally useful thing to have, even separate from this project. (I'm already doing this scanning anyway). So might publish a starter version of  it separately, call it something like `flutter_clone` or `flown`. Any suggestions?

**Comment by mmcc007** [comment]
Try initial release of `flown`
```
pub global activate flown
```

**Comment by zerox1212** [comment]
That's a nice collection of examples. Thanks for that it will be helpful.

Perhaps you are correct, but I still would prefer nice bare bone templates. It's especially helpful for new people. Since I'm just starting the redesign of my app I might first publish it as a template. For me having a Firebase template would save a lot of time, because right now I feel like I'm wasting some effort just creating a basic Firebase login page with user management. The Firebase Auth example from flutter leaves some things to be desired...

**Comment by mmcc007** [comment]
I found the easiest way to start with Firebase Auth is to get the example app it comes with working. Since I last looked there is no one place that documents the entire config process. I attempted to but something in one place in this [comment](https://github.com/flutter/plugins/pull/606#issuecomment-402878854). There is also [this](https://github.com/flutter/plugins/pull/606#issuecomment-402878854) more current article.

**Comment by zerox1212** [comment]
I started a repo that I want to try with cookiecutter. However I'm finding that I absolutely suck at dart/flutter. I want to use scoped model because it makes more sense to me as far as organization.

https://github.com/zerox1212/cookiecutter-flutter-firebase

If anyone on here is willing to give me some direction I would be happy to do the time consuming work to make the template. First step is if someone could tell me if I'm even close with this https://gist.github.com/zerox1212/fb961ee09b9869cb29b8a9894a90ea57. All I want is a simple scoped model for firebase login or anonymous login. If anyone wants to help we can continue at https://github.com/zerox1212/cookiecutter-flutter-firebase/issues/1 so as not to pollute this issue any further. Thanks

**Comment by S1r-Lanzelot** [comment]
Another flutter newbie here to say that yes, at first, I was pretty confused by the breaking up of the example code into smaller libraries however (once I figured out what was going on) it was useful to see how one would structure the code once the app grows. So definitely keep it as is.

The script that @mmcc007 would be really slick! Thanks guys for spending your valuable time to help others.

**Comment by mmcc007** [comment]
It's been released. Give it a try and let me know of any [issues](https://github.com/mmcc007/flown/issues)
```
pub global activate flown
```

**Comment by S1r-Lanzelot** [comment]
@mmcc007 missed that in the thread, awesome, I will let you know. Thank you! :pray:

**Comment by hrsma2izozo** [comment]
@mmcc007 Thank you for your great work.

I made the `vanilla_project` by flown, but the created project has the error `Target URI doesn't exists` in the local repository ``

**Comment by mmcc007** [comment]
@hrsma2izozo I created the vanilla project using flown and installed it on an android emulator and played around with it. It did not report an error.

I'd recommend opening an new issue on this and provide enough information about what actions you took so that the error can be recreated by someone else (or try to).

Including the output from `flutter doctor -v` in the issue helps recreate the problem.

👍

**Comment by hrsma2izozo** [comment]
@mmcc007 Thank you for your kind reply. I'll do that.

**Comment by brianegan** [comment]
Hey all, since Flown is working, I'm gonna close this out for now! Please let me know if ya still need help.

**Comment by relativityboy** [comment]
SG!
